apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-angular
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/name: kubernetes-angular
      layer: frontend
  replicas: 1
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: kubernetes-angular
        layer: frontend
    spec:
      containers:
      - name: kubernetes-angular
        image: kubernetes-angular
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-angular
  labels:
    app: kubernetes-angular
spec:
  type: NodePort
  ports:
  - nodePort: 30600
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: kubernetes-angular
    layer: frontend