apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-restful-api
spec: 
  selector: 
    matchLabels: 
      app.kubernetes.io/name: spring-restful-api
      layer: mid-tier
  replicas: 1
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: spring-restful-api
        layer: mid-tier
    spec:
      containers: 
      - name: spring-restful-api
        image: mithilcshah/spring-restful-api:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-restful-api-service
  labels:
    app.kubernetes.io/name: spring-restful-api-service
    layer: mid-tier
spec:
  type: NodePort
  ports:
  - nodePort: 30510
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: spring-restful-api
    layer: mid-tier

         
