kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-pods-get
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
# This role binding allows "frontend" user to list pods in the "backend" namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-pods
subjects:
- kind: User
  name: frontend
  apiGroup: ""
roleRef:
  kind: ClusterRole 
  name: backend-pods-get # this must match the name of the Role 
  apiGroup: rbac.authorization.k8s.io