
apiVersion: v1
kind: Pod
metadata:
  name: kub-secret-vol-file-pod
spec:
 containers:
 - name: spring-restful-api-kub-secret-vol
   image: nginx
   imagePullPolicy: IfNotPresent
   volumeMounts:
   - name: ssh-key-file-vol
     mountPath: /opt/ssh-keys/
 volumes:
   - name: ssh-key-file-vol
     secret:
       secretName: ssh-key-file
            
        
