apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-restful-api-kub-configmap-file
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/name: spring-restful-api-kub-configmap-file
  replicas: 1
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: spring-restful-api-kub-configmap-file
    spec:
      containers:
      - name: spring-restful-api-kub-configmap-file
        image: mithilcshah/spring-restful-api-kub-configmap:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: spring.config.location
          value: file:/opt/config/
        volumeMounts:
        - name: application-properties
          mountPath: /opt/config
      volumes:
        - name: application-properties
          configMap:
            name: spring-restful-api-kub-configmap-file
            items:
              - key: application.properties
                path: application.properties
        
---
apiVersion: v1
kind: Service
metadata:
  name: spring-restful-api-service
  labels:
    app.kubernetes.io/name: spring-restful-api-kub-configmap-file
spec:
  type: NodePort
  ports:
  - nodePort: 30520
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: spring-restful-api-kub-configmap-file
