apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-cleaner
  labels:
    app: log-cleaner
spec:
  selector:
    matchLabels:
      name: log-cleaner
  template:
    metadata:
      labels:
        name: log-cleaner
    spec:
      containers:
      - name: log-cleaner
        image: debian
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]

