apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-static-website
spec:
  selector: 
    matchLabels:
      app: static-website
  replicas: 2
  template: 
    metadata:
      labels:
        app: static-website
    spec:
      volumes:
      - name: htdocs
        emptyDir: {}
      containers:
      - name: static-website
        image: kubernetes-static-website:latest
        volumeMounts:
        - name: htdocs
          mountPath: /usr/local/apache2/htdocs/
        imagePullPolicy: Never
        ports:
        - containerPort: 80
      - name: update-html
        image: update-html:latest
        volumeMounts:
        - name: htdocs
          mountPath: /usr/local/apache2/htdocs/
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: static-website-service
  labels:
    app: static-website-service
spec:
  type: NodePort
  ports:
  - nodePort: 30500
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: static-website