apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.company.env }}
  annotations:
    length: {{ len .Values.company.team }}
    machine: {{ .Values.company.machine | default "HP" }}
    team: {{ len .Values.company.team | print .Values.company.env }}
